name: 'TestParty: Reporter'
description: 'Scan URLs for accessibility violations.'
inputs:
  testparty_token:
    description: 'API token for authentication'
    required: true
  urls:
    description: 'Comma-separated list of URLs to scan'
    required: true
  auth_type:
    description: 'Type of authentication to use'
    required: false
    default: 'email'
  auth_url:
    description: 'URL for basic authentication'
    required: false
  email:
    description: 'Email for basic authentication'
    required: false
  password:
    description: 'Password for basic authentication'
    required: false
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.testparty_token }}
    - ${{ inputs.urls }}
    - ${{ inputs.auth_type }}
    - ${{ inputs.auth_url }}
    - ${{ inputs.email }}
    - ${{ inputs.password }}