name: 'TestParty: Reporter'
description: 'Scan URLs for accessibility violations.'
inputs:
  testparty_token:
    description: 'API token for authentication'
    required: true
  repository_name:
    description: 'Name of the repository'
    required: true
  repository_id:
    description: 'ID of the repository'
    required: true
  urls:
    description: 'JSON of urls with steps'
    required: true
  setup:
    description: 'JSON of setup steps'
    required: false
    default: '[]'
  teardown:
    description: 'JSON of teardown steps'
    required: false
    default: '[]'
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.testparty_token }}
    - ${{ inputs.repository_name }}
    - ${{ inputs.repository_id }}
    - ${{ inputs.urls }}
    - ${{ inputs.setup }}
    - ${{ inputs.teardown }}