name: Test the TestParty Reporter
on:
  schedule:
    # This example runs every 6 hours
    - cron: '0 0 * * *'
  # Optionally keep workflow_dispatch to allow manual triggers
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Reporter
        uses: ./
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: |
            [
              {
                  "url": "testparty.ai",
                  "steps": []
              }
            ]