name: Test the Reporter
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: TestParty Reporter
        uses: test-party/reporter@v0.0.1-alpha.4
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: |
            [
              {
                  "url": "https://arenaclub.com/",
                  "steps": [
                    {
                      "type": "button",
                      "selector": "button",
                      "text": "Log in",
                       "scanAfterAction": false
                    },
                    {
                      "type": "input",
                      "inputType": "email"
                      "value": "jason@testparty.ai"
                      "scanAfterAction": false
                    },
                    {
                      "type": "input",
                      "inputType": "password"
                      "value": "password"
                      "scanAfterAction": false
                    },
                    {
                      "type": "button",
                      "selector": "button",
                      "text": "SIGN IN",
                      "scanAfterAction": true
                    }
                  ]
              },
              {
                  "url": "https://arenaclub.com/marketplace?tab=all&sortBy=featured&page=1&query=",
                  "steps": []
              }
            ]