name: TestParty Reporter
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestParty Reporter
        uses: ./
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: |
            - url: https://testparty.ai
              steps: []
          setups: |
            - scanAfterAction: false
              type: button
              selector: "Login"
              text: ""
          teardowns: |
            []