name: Test the Reporter
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestParty Reporter
        uses: ./
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: |
            [
              {
                  "url": "https://arenaclub.com/",
                  "steps": []
              },
              {
                  "url": "https://arenaclub.com/marketplace?tab=all&sortBy=featured&page=1&query=",
                  "steps": []
              }
            ]
          setup: |
            [
              {
                  "url": "https://arenaclub.com/",
                  "steps": [
                    {
                      "type": "button",
                      "selector": "span",
                      "text": "Log in",
                      "scanAfterAction": false
                    },
                    {
                      "type": "input",
                      "selector": {
                        "type": "type",
                        "inputType": "email"
                      },
                      "value": "jason@testparty.ai",
                      "scanAfterAction": false
                    },
                    {
                      "type": "input",
                      "selector": {
                        "type": "type",
                        "inputType": "password"
                      },
                      "value": "TestParty123!",
                      "scanAfterAction": false
                    },
                    {
                      "type": "button",
                      "selector": "button",
                      "text": "SIGN IN",
                      "scanAfterAction": true
                    }
                  ]
              }
            ]
          teardown: |
            [
              {
                  "url": "https://arenaclub.com/",
                  "steps": [
                    {
                      "type": "button",
                      "selector": "span",
                      "text": "Log Out",
                      "scanAfterAction": false
                    }
                  ]
              }
            ]