name: Test the TestParty Reporter
on:
  schedule:
    # This example runs every 6 hours
    - cron: '0 */6 * * *'
  # Optionally keep workflow_dispatch to allow manual triggers
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Reporter
        uses: ./
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          urls: |
            [
              {
                  "url": "https://accessibility-test-company-with-medical-whwuzy.pasito.ai/r/HU6ZN8IotrMS",
                  "steps": []
              },
              {
                  "url": "https://app.joinpasito.com/accessibility-test-company-with-medical-whwuzy/recommendations/new",
                  "steps": [
                      {
                          "selector": "button",
                          "text": "Agree and continue",
                          "scanAfterAction": true
                      },
                      {
                          "selector": "button",
                          "text": "Skip",
                          "scanAfterAction": true
                      }
                  ]
              }
            ]