name: Arena Club's Accessibility Reporter
on:
  schedule:
    - cron: '0 0 1 1 * */2'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: TestParty Reporter
        uses: test-party/reporter@v0.0.1-alpha.4
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: |
            [
              {
                  "url": "https://arenaclub.com/",
                  "steps": [
                    {
                      "type": "button",
                      "selector": "button",
                      "text": "Log in",
                       "scanAfterAction": false
                    },
                    {
                      "type": "input",
                      "inputType": "email"
                      "value": "jason@testparty.ai"
                      "scanAfterAction": false
                    },
                    {
                      "type": "input",
                      "inputType": "password"
                      "value": "password"
                      "scanAfterAction": false
                    },
                    {
                      "type": "button",
                      "selector": "button",
                      "text": "SIGN IN",
                      "scanAfterAction": true
                    }
                  ]
              },
              {
                  "url": "https://arenaclub.com/marketplace?tab=all&sortBy=featured&page=1&query=",
                  "steps": []
              },
              {
                  "url": "https://arenaclub.com/auction/win-feed",
                  "steps": []
              },
              {
                  "url": "https://arenaclub.com/showrooms",
                  "steps": []
              },
              {
                  "url": "https://arenaclub.com/showrooms/derekjeter49245/collection",
                  "steps": []
              },
              {
                  "url": "https://arenaclub.com/showrooms/derekjeter49245/list",
                  "steps": []
              },
              {
                  "url": "https://arenaclub.com/showrooms/derekjeter/collection/a17cf944-482d-4fc3-ae4c-8ac631621b41",
                  "steps": []
              },
              {
                  "url": "https://arenaclub.com/cards/football-2014-topps-chrome-davante-adams-8AC002253413",
                  "steps": []
              },
              {
                  "url": "https://arenaclub.com/offers/71304373-2282-4c40-8e0a-163fef2d69ac/edit",
                  "steps": []
              }
            ]