name: Pasito's Accessibility Reporter
on:
  schedule:
    # This example runs every 6 hours
    - cron: '0 0 * * *'
  # Optionally keep workflow_dispatch to allow manual triggers
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: TestParty Reporter
        uses: test-party/reporter@v0.0.1-alpha.5
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: |
            [
              {
                  "url": "https://testparty.ai",
                  "steps": []
              }
            ]