name: TestParty Reporter
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestParty Reporter
        uses: test-party/reporter@ecs-version
        with:
          testparty_token: ${{ secrets.TESTPARTY_TOKEN }}
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: |
            [
              {
                "url": "https://www.understood.org/en/articles/6-things-to-know-about-private-schools-and-special-education",
                "steps": []
              }
            ]
          setup: |
            []
          teardown: |
            []