name: TestParty Reporter
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestParty Reporter
        uses: test-party/reporter@main
        with:
          testparty_token: d715e77d-4d4b-4ece-b1f5-0b4cf4bb3bd0
          repository_name: 'Aunt Flow (WordPress)''
          repository_id: 111
          urls: |
              [
                {
                  "url": "https://goauntflow.com",
                  "steps": []
                },
                {
                  "url": "https://goauntflow.com/donation-program/",
                  "steps": []
                },
                {
                  "url": "https://goauntflow.com/blog/case-study/lake-bluff-public-library/",
                  "steps": []
                }
              ]
          setup: |
            []
          teardown: |
            []